#%RAML 1.0
title: coin-monitor-process-api
types:
  getCryptos: !include data-type/get-cryptos-responses-200-data-type.raml
  updateCryptos: !include data-type/update-cryptos-responses-200-data-type.raml
  checkPrice: !include data-type/check-price-responses-200-data-type.raml
  errorsType: !include data-type/errors-data-type.raml

traits:
  errors:
    responses:
      400:
        body:
          application/json:
            type: errorsType
            example: !include examples/responses-400-example.json
      401:
        body:
          application/json:
            type: errorsType
            example: !include examples/responses-401-example.json
      403:
        body:
          application/json:
            type: errorsType
            example: !include examples/responses-403-example.json
      408:
        body:
          application/json:
            type: errorsType
            example: !include examples/responses-408-example.json
      429:
        body:
          application/json:
            type: errorsType
            example: !include examples/responses-429-example.json
      500:
        body:
          application/json:
            type: errorsType
            example: !include examples/responses-500-example.json

/getCryptos:


  displayName: Get a paginated list of all active cryptocurrencies
  description: Returns a paginated list of all active cryptocurrencies with latest market data
  get:

    queryParameters:
      slug:
        description: Query with multiple slugs
        required: true
        type: string
        example: bitcoin

    responses:
      200:
        description: 
        body:
          application/json:
            type: getCryptos
            example: !include examples/get-cryptos-responses-200-example.json
    is: [errors]


/updateCryptos:
  displayName: Update object of all active cryptocurrencies
  description: Returns a paginated list of all active cryptocurrencies with latest market data
  /{id}:
      displayName: Update object of all active cryptocurrencies
      description: Returns a paginated list of all active cryptocurrencies with latest market data
      get:
        responses:
          200:
            description: 
            body:
              application/json:
                type: updateCryptos
                example: !include examples/update-cryptos-id-responses-200-example.json
        is: [errors]

/checkPrice:
  displayName: Checks the difference between the values
  description: Returns a paginated list of all active cryptocurrencies with new prices and difference between the values
  /{id}:
    displayName: Update object of all active cryptocurrencies
    description: Returns a paginated list of all active cryptocurrencies with latest market data
    get:
      responses:
        200:
          description: 
          body:
              application/json:
                type: checkPrice
                example: !include examples/check-prices-responses-200-example.json
      is: [errors]

      
/deleteCryptos:
  displayName: Update object of all active cryptocurrencies
  description: Returns a paginated list of all active cryptocurrencies with latest market data
  /{id}:
      displayName: Update object of all active cryptocurrencies
      description: Returns a paginated list of all active cryptocurrencies with latest market data
      get:
        responses:
          200:
            description: 
            body:
              application/json:
                type: string
                example: success
        is: [errors]




  