#%RAML 1.0
title: coin-monitor-process-api
types:
  getCryptos: !include data-type/create-cryptos-responses-201-data-type.raml
  updateCryptos: !include data-type/update-cryptos-responses-201-data-type.raml
  checkPrice: !include data-type/check-cryptos-price-responses-201-data-type.raml
  readCryptos: !include data-type/read-cryptos-responses-200-data-type.raml
  errorsType: !include data-type/errors-data-type.raml
  deleteCryptos: !include data-type/delete-cryptos-responses-200-data-type.raml

traits:
  errors:
    responses:
      400:
        body:
          application/json:
            type: errorsType
            example: !include examples/responses-400-example.json
      401:
        body:
          application/json:
            type: errorsType
            example: !include examples/responses-401-example.json
      403:
        body:
          application/json:
            type: errorsType
            example: !include examples/responses-403-example.json
      408:
        body:
          application/json:
            type: errorsType
            example: !include examples/responses-408-example.json
      429:
        body:
          application/json:
            type: errorsType
            example: !include examples/responses-429-example.json
      500:
        body:
          application/json:
            type: errorsType
            example: !include examples/responses-500-example.json

/createCryptos:
  displayName: Create a paginated list of all active cryptocurrencies
  description: Create a paginated list of all active cryptocurrencies in DB
  
  get:
    queryParameters:
      slug:
        description: describe which cryptocurrency you want to receive
        required: true
        type: string
        example: bitcoin
      sortBy:
        description: query parameter for sorting by price or volume24h
        required: false
        type: string
        enum: [price, volume]

    responses:
      201:
        description: put in DB information about cryptocurrencies
        body:
          application/json:
            type: getCryptos
            example: !include examples/create-cryptos-responses-201-example.json
    is: [errors]

/readCryptos:
  displayName: Get a paginated list of cryptocurrencies from DB by id
  description: Returns a paginated list of all active cryptocurrencies
  /{id}:
      get:
        responses:
          200:
            description: 
            body:
              application/json:
                type: readCryptos
                example: !include examples/read-cryptos-responses-200-example.json
        is: [errors]
  
/updateCryptos:
  displayName: Update object of all active cryptocurrencies
  description: update in DB information, add fields "description", "developmentStatus", "proofType", "orgStructure" to cryptocurrencies
  /{id}:
      get:
        responses: 
          201:
            description: Returns a paginated list of all active cryptocurrencies with latest market data
            body:
              application/json:
                type: updateCryptos
                example: !include examples/update-cryptos-responses-201-example.json
        is: [errors]

/checkCryptosPrice:
  displayName: Checks the difference between the price and value24h
  description: update in DB information, add fields "oldDate", "newDate", "dateDifference", "orgStructure" to cryptocurrencies
  /{id}:
    get:
      responses:
        201:
          description: Returns a paginated list of all active cryptocurrencies with new prices, date and difference between the values
          body:
              application/json:
                type: checkPrice
                example: !include examples/check-cryptos-prices-responses-201-example.json
      is: [errors]

      
/deleteCryptos:
  displayName: delete object of cryptocurrencies by id
  description: delete object of cryptocurrencies by id
  /{id}:
      get:
        responses:
          200:
            description: return success or not was deleting
            body:
              application/json:
                type: deleteCryptos
                example: !include examples/delete-cryptos-responses-200-example.json
        is: [errors]




  