#%RAML 1.0 DataType

type: object
properties:
  oldDate: string
  newDate: string
  dateDifference: string
  data: 
    items:
      properties:
        name: string
        symbol: string
        supply: string
        developmentStatus: string
        proofType: string
        orgStructure: string
        coin_market_price_oldPriceUsd: string
        coin_cap_price_oldPriceUsd: string
        coin_market_price_newPriceUsd: string
        coin_cap_price_newPriceUsd: string
        coin_market_price_priceDifference: string
        coin_cap_price_priceDifference: string
        coin_market_volume24h: string
        coin_cap_volume24h: string