#%RAML 1.0 DataType

type: object
properties:
  date: string
  data:
    properties:
      BTC:
        properties:
          supply: integer
          development_status: string
          proof_type: string
          org_structure: string
          coin-market-cap-api:
            properties:
              priceUsd: string
              volumeUsd24Hr: string
              changePercent24Hr: string
          coin-cap-api:
            properties:
              priceUsd: string
              volumeUsd24Hr: string
              changePercent24Hr: string